name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/Alschy/index.json
    - name: Build common
      run: dotnet build /src/common --configuration Release
    - name: Build core
      run: dotnet build /src/server-core --configuration Release
    - name: Build utils
      run: dotnet build /src/utils --configuration Release
    - name: Build mongo
      run: dotnet build /src/mongo-db --configuration Release
    - name: Build web client
      run: dotnet build /src/web-client --configuration Release
    - name: Publish
      run: dotnet nuget push -k {{ secrets.NUGET_API_KEY }}
