name: .NET Core

on:
  push:
    branches: [ release ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: mkdir artifacts
      run: mkdir ./artifacts
    - name: Build common
      run: dotnet build --configuration Release -o ./artifacts ./src/common/*.sln
    - name: Build server-core
      run: dotnet build --configuration Release -o ./artifacts ./src/server-core/*.sln
    - name: Build utils
      run: dotnet build --configuration Release -o ./artifacts ./src/utils/*.sln
    - name: Build mongo-db
      run: dotnet build --configuration Release -o ./artifacts ./src/mongo-db/*.sln
    - name: Build web-client
      run: dotnet build --configuration Release -o ./artifacts ./src/web-client/*.sln
    - name: Publish
      run: dotnet nuget push ./artifacts/**/*.nupkg -k ${{ secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate 
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: LocalizeServer-Artifacts
        # Directory containing files to upload
        path: ./artifacts
   
